/**
 * The media kinds supported by TheIntroDB.
 */
export const MEDIA_TYPES = ['movie', 'tv'] as const;

/**
 * The segment kinds supported by TheIntroDB.
 */
export const SEGMENT_TYPES = ['intro', 'recap', 'credits', 'preview'] as const;

/**
 * Submission states returned by the API.
 */
export const SUBMISSION_STATUSES = ['pending', 'accepted', 'rejected'] as const;

/**
 * Canonical media type returned by the API.
 */
export type MediaType = (typeof MEDIA_TYPES)[number];

/**
 * Canonical segment type accepted by the API.
 */
export type SegmentType = (typeof SEGMENT_TYPES)[number];

/**
 * Review status assigned to a submission.
 */
export type SubmissionStatus = (typeof SUBMISSION_STATUSES)[number];

/**
 * The API accepts either a single season/episode number or a string expression.
 */
export type EpisodeSelection = number | string;

/**
 * Raw timestamp object exactly as returned by `/media`.
 * `null` values are preserved here and normalized later.
 */
export interface SegmentTimestampRaw {
  /** Start offset in milliseconds. `null` means "starts at the beginning". */
  start_ms: number | null;
  /** End offset in milliseconds. `null` means "continues to end of media". */
  end_ms: number | null;
  confidence?: number | null;
  submission_count?: number | null;
}

/**
 * Normalized timestamp shape exposed by this package.
 */
export interface NormalizedSegmentTimestamp {
  /** Normalized start time in milliseconds. `null` start values become `0`. */
  startMs: number;
  /** End time in milliseconds, or `null` when the segment runs to the media end. */
  endMs: number | null;
  /** Duration in milliseconds when both endpoints are known; otherwise `null`. */
  durationMs: number | null;
  /** True when the source timestamp used `null` for the start. */
  startsAtBeginning: boolean;
  /** True when the source timestamp used `null` for the end. */
  endsAtMediaEnd: boolean;
  confidence?: number | null;
  submissionCount?: number | null;
}

/**
 * Raw `/media` response shape from the OpenAPI document.
 */
export interface MediaResponseRaw {
  /** TMDB identifier for the movie or TV series. */
  tmdb_id: number;
  /** The requested media kind. */
  type: MediaType;
  /** Season number for TV responses only. */
  season?: number | null;
  /** Episode number for TV responses only. */
  episode?: number | null;
  /** Intro segments, if any submissions exist for this segment type. */
  intro?: SegmentTimestampRaw[];
  /** Recap segments, if any submissions exist for this segment type. */
  recap?: SegmentTimestampRaw[];
  /** Credits segments, if any submissions exist for this segment type. */
  credits?: SegmentTimestampRaw[];
  /** Preview segments, if any submissions exist for this segment type. */
  preview?: SegmentTimestampRaw[];
}

/**
 * Normalized media record returned by this package.
 */
export interface MediaRecord {
  /** TMDB identifier for the media item. */
  tmdbId: number;
  /** Media type for the record. */
  type: MediaType;
  /** Season number for TV lookups. */
  season?: number;
  /** Episode number for TV lookups. */
  episode?: number;
  /** Normalized intro timestamps. */
  intro: NormalizedSegmentTimestamp[];
  /** Normalized recap timestamps. */
  recap: NormalizedSegmentTimestamp[];
  /** Normalized credits timestamps. */
  credits: NormalizedSegmentTimestamp[];
  /** Normalized preview timestamps. */
  preview: NormalizedSegmentTimestamp[];
}

/**
 * Standard error shape used by the API.
 */
export interface ErrorResponse {
  /** Human-readable error message. */
  error: string;
  /** Extra validation or server details when provided by the API. */
  details?: string;
  /** Optional machine-readable code for some error types. */
  code?: string;
  /** Human-readable retry guidance returned on some rate-limit responses. */
  retry_after?: string;
}

/**
 * Raw submission object returned by `/submit`.
 */
export interface SubmissionDataRaw {
  /** Submission UUID generated by the service. */
  id: string;
  /** TMDB identifier for the target media. */
  tmdbId: number;
  /** Media type for the submission. */
  type: MediaType;
  /** Segment type that was submitted. */
  segment: SegmentType;
  /** Season number for TV submissions. */
  season?: number | null;
  /** Episode number for TV submissions. */
  episode?: number | null;
  videoDurationMs?: number | null;
  /** Start time in milliseconds. `null` means start of media for intro/recap. */
  startMs?: number | null;
  /** End time in milliseconds. `null` means end of media for credits/preview. */
  endMs?: number | null;
  /** Moderation status assigned to the submission. */
  status: SubmissionStatus;
  /** Relative weight used by the backend when averaging timestamps. */
  weight: number;
}

/**
 * Normalized submission data returned by this package.
 */
export interface SubmissionData {
  /** Submission UUID generated by the service. */
  id: string;
  /** TMDB identifier for the target media. */
  tmdbId: number;
  /** Media type for the submission. */
  type: MediaType;
  /** Segment type that was submitted. */
  segment: SegmentType;
  /** Season number for TV submissions. */
  season?: number;
  /** Episode number for TV submissions. */
  episode?: number;
  videoDurationMs: number | null;
  /** Normalized start time in milliseconds. */
  startMs: number;
  /** End time in milliseconds, or `null` when the segment reaches media end. */
  endMs: number | null;
  /** Duration in milliseconds when both endpoints are known; otherwise `null`. */
  durationMs: number | null;
  /** True when the source timestamp used `null` for the start. */
  startsAtBeginning: boolean;
  /** True when the source timestamp used `null` for the end. */
  endsAtMediaEnd: boolean;
  /** Moderation status assigned by the service. */
  status: SubmissionStatus;
  /** Relative weight applied by the backend. */
  weight: number;
}

/**
 * Raw `/submit` success response.
 */
export interface SubmissionResponseRaw {
  submissions: SubmissionDataRaw[];
}

/**
 * Normalized `/submit` success response exposed by this package.
 */
export interface SubmissionResponse {
  submissions: SubmissionData[];
}

/**
 * Parameters accepted by `getMedia()`.
 * Use `tmdbId` whenever possible; `imdbId` is supported but can add lookup latency.
 */
export interface GetMediaParams {
  /** Preferred canonical identifier for the media item. */
  tmdbId?: number;
  /** Optional IMDB identifier used when TMDB ID is unavailable. */
  imdbId?: string;
  /** Optional TVDB identifier used when TMDB ID is unavailable. */
  tvdbId?: number;
  /** Season number for TV episode lookups. */
  season?: number;
  /** Episode number for TV episode lookups. */
  episode?: number;
  durationMs?: number;
}

/**
 * Common submission fields shared by seconds-based and milliseconds-based inputs.
 */
export interface SubmitMediaBase {
  /** TMDB identifier for the media item. */
  tmdbId: number;
  /** Optional IMDB identifier sent through to the API. */
  imdbId?: string;
  /** Media type for the submission. */
  type: MediaType;
  /** Segment type being submitted. */
  segment: SegmentType;
  /** Season selector for TV submissions. Omit for movies. */
  season?: EpisodeSelection;
  /** Episode selector for TV submissions. Omit for movies. */
  episode?: EpisodeSelection;
  videoDurationMs?: number | null;
}

/**
 * Submission input that uses seconds with optional decimal precision.
 */
export interface SubmitMediaSecondsInput extends SubmitMediaBase {
  /** Start time in seconds. `null` is allowed for intro/recap to mean the beginning. */
  startSec?: number | null;
  /** End time in seconds. `null` is allowed for credits/preview to mean media end. */
  endSec?: number | null;
  startMs?: never;
  endMs?: never;
}

/**
 * Submission input that uses integer millisecond values.
 */
export interface SubmitMediaMillisecondsInput extends SubmitMediaBase {
  startSec?: never;
  endSec?: never;
  /** Start time in milliseconds. `null` is allowed for intro/recap to mean the beginning. */
  startMs?: number | null;
  /** End time in milliseconds. `null` is allowed for credits/preview to mean media end. */
  endMs?: number | null;
}

/**
 * Union of all accepted submission payload shapes.
 */
export type SubmitMediaTimestampInput =
  | SubmitMediaSecondsInput
  | SubmitMediaMillisecondsInput;

/**
 * Serialized request body sent to `/submit`.
 */
export interface SubmissionRequestPayload {
  /** TMDB identifier for the media item. */
  tmdb_id: number;
  /** Optional IMDB identifier used by the backend for linking. */
  imdb_id?: string;
  /** Media type for the submission. */
  type: MediaType;
  /** Segment type being submitted. */
  segment: SegmentType;
  /** Season selector for TV submissions. */
  season?: EpisodeSelection;
  /** Episode selector for TV submissions. */
  episode?: EpisodeSelection;
  video_duration_ms?: number | null;
  /** Start time in milliseconds, or `null` when the segment starts at the beginning. */
  start_ms?: number | null;
  /** End time in milliseconds, or `null` when the segment runs to media end. */
  end_ms?: number | null;
}

/**
 * Parsed rate-limit and usage-limit metadata from response headers.
 */
export interface RateLimitDetails {
  /** Max requests allowed in the current rate-limit window. */
  rateLimit: number | null;
  /** Remaining requests in the current rate-limit window. */
  rateLimitRemaining: number | null;
  /** Seconds until the rate-limit window resets. */
  rateLimitResetSeconds: number | null;
  /** Max requests allowed in the current usage window. */
  usageLimit: number | null;
  /** Remaining requests in the current usage window. */
  usageRemaining: number | null;
  /** Seconds until the usage window resets. */
  usageResetSeconds: number | null;
}

/**
 * Minimal header reader interface used by the internal transport wrapper.
 */
export interface HeadersLike {
  /** Returns the header value for the given name, or `null` if absent. */
  get(name: string): string | null;
}

/**
 * Minimal response shape required from the injected fetch implementation.
 */
export interface FetchResponseLike {
  /** True when the HTTP status is in the 2xx range. */
  ok: boolean;
  /** HTTP status code. */
  status: number;
  /** Human-readable HTTP status text. */
  statusText: string;
  /** Header access helper. */
  headers: HeadersLike;
  /** Reads the response body as text. */
  text(): Promise<string>;
}

/**
 * Minimal fetch signature accepted by the client.
 */
export type FetchLike = (
  input: string,
  init?: {
    method?: string;
    headers?: Record<string, string>;
    body?: string;
    signal?: unknown;
  }
) => Promise<FetchResponseLike>;

/**
 * TIDB logger hook used for request lifecycle messages.
 * Pass `console` directly if you want simple runtime logging.
 */
export interface TIDBLogger {
  /** Verbose diagnostic logging. */
  debug?(message: string, context?: Record<string, unknown>): void;
  /** Informational request lifecycle logging. */
  info?(message: string, context?: Record<string, unknown>): void;
  /** Non-fatal warnings. */
  warn?(message: string, context?: Record<string, unknown>): void;
  /** Errors that are about to be surfaced to the caller. */
  error?(message: string, context?: Record<string, unknown>): void;
}

/**
 * Shared TIDB transport options for standalone calls and client instances.
 */
export interface TIDBTransportOptions {
  /** Override for the API base URL. Defaults to the production v3 endpoint. */
  baseUrl?: string;
  /**
   * The current user's API key.
   * `getMedia()` may use it optionally to include that user's pending submissions.
   * `submitMediaTimestamp()` requires it so submissions are credited to that user.
   */
  apiKey?: string;
  /** Additional headers merged into every request. */
  headers?: Record<string, string>;
  /** Custom fetch implementation for Node, tests, or alternate runtimes. */
  fetch?: FetchLike;
  /** Optional logger for auth and request lifecycle messages. */
  logger?: TIDBLogger;
  /** Abort signal forwarded to the underlying fetch implementation. */
  signal?: unknown;
}

/**
 * Default options applied when creating a reusable TIDB client instance.
 */
export type TIDBClientOptions = Omit<TIDBTransportOptions, 'signal'>;

/**
 * Per-request overrides supported by TIDB client methods.
 */
export type TIDBRequestOptions = Partial<
  Pick<TIDBTransportOptions, 'apiKey' | 'headers' | 'logger' | 'signal'>
>;

/**
 * Public TIDB client contract exposed by `createIntroDbClient()`.
 */
export interface TIDBClient {
  /**
   * Fetches media timestamps.
   * This endpoint is public, but passing the current user's API key causes the
   * response to include that user's pending submissions in addition to accepted ones.
   */
  getMedia(
    params: GetMediaParams,
    requestOptions?: TIDBRequestOptions
  ): Promise<MediaRecord>;
  /**
   * Submits timestamps on behalf of the current user.
   * The caller must provide that user's API key either on the client or per request.
   */
  submitMediaTimestamp(
    input: SubmitMediaTimestampInput,
    requestOptions?: TIDBRequestOptions
  ): Promise<SubmissionResponse>;
}
